name: app_yolo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  http: ^1.4.0
  image: ^4.5.4
  path_provider: ^2.1.5
  exif: ^3.3.0
  flutter_vision: ^1.1.4
  google_mlkit_text_recognition: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/models/best_float32.tflite
  - assets/models/labels.txt